# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: Preview Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          publish-dir: './public'
          production-branch: refresh
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
